### PR TITLE
Script to fetch DNS records from various services

### PR DESCRIPTION
**Pull request by mehalter**
This also adds the ability to pipe arguments through `stdin` to `dns_verify`

Change-type: minor
Signed-off-by: Micah Halter <micah@balena.io>

### CODE REVIEW

**Review by 20k-ultra — COMMENTED** [review]
I'm not sure if moving the services into a services folder is worth it since now you have to make sure you move that folder around with the shell code...thoughts ? we can remove the commit.

**Review by 20k-ultra — COMMENTED** [review]
I saw that dns_verify returns exit code 0 if it isn't able to perform its logic (such as a cloudflare token not being set). I'd want these to not falsely pass.

**Comment by mehalter** [comment]
> I'm not sure if moving the services into a services folder is worth it since now you have to make sure you move that folder around with the shell code...thoughts ? we can remove the commit.

Yeah I think keeping portability is a good thing especially when it comes to Sharing. We should probably keep it to a single file

**Comment by mehalter** [comment]
> I saw that dns_verify returns exit code 0 if it isn't able to perform its logic (such as a cloudflare token not being set). I'd want these to not falsely pass.

Yeah this is in the TODO block at the top of the file :)

**Review by 20k-ultra — CHANGES_REQUESTED** [review]
the dns_fetch script will happily exit when it doesn't get domains

```
~/Projects/orca/dns_fetch$ ./dns_fetch.sh -s cloudflare                                                                  ✹dns_fetch 
dns_fetch.sh: Error: Cloudflare token or email+auth key are not provided. Please set the necessary environment variables
[]
~/Projects/orca/dns_fetch$ echo $?                                                                                       ✹dns_fetch 
0
```

**Review by 20k-ultra — APPROVED** [review]

**Pull request merged**
